travis:
  secure:
    BINSTAR_TOKEN: LpJdoF2UtbQP/mYN2Bf+j7lEb+GbdcMue4zZ5wep9w4qblwsa0VesdunoJFIBeB0GXI85u18Z37EyTTkhCXZKGH9zkme/PsTyXjan9opEz4JlPP9bjoA4tLvn23XMAWA8Pey+GWEE+mgw+okavEoWQYnqzvxEol/FtEaZYXlWK+wyUr69a70Ee0Oj+J+N9JKUDlwhnSRVNkOaRrsEiUDxGPkg1h+x7P5LjxjzJU1gv2qJB3lS4TwRa0GDdlgPtau45kFi5ZZ+t/PmNa9ywK0LmLok4u+BFKf/BCZMVfJGsHNuhhF25VKSR71t17uXFNjd9YQlQk2V+AEGdVJ9xGUZhB927L69q6UqFOskV+pgHQEYP8t7S3lWwj8QB1qcieNHYVo+19QOBOsghXWhNnYDbdRh+SvJIno/bM0WHL4EZJGpeRSSQZgEJ2nwGA/6EUCes4zuZIjZeeB2vDTV5VmdByznhaVkRIa9U0p43nTxhIg7pjq77mKtFVZ/PXqB3vq90dUN336wsfYr9Tra9adOOZUNq0JF3wASyn34fpm88bLWmX6CsGGGGY8nLUr9juRVfFk3Rdx/ghBXRuXCwE8Z+6p7Hru0g/fznZkX1Kc/qrnLhQki5tq4vLyhyezCUocCSrvgK6WYuhhjnEHmUBle3vh106exKT/ATiOhQZo4QY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
